plugins {
    id "com.android.application"
}

android {
    namespace "com.dele.spanishlearning"
    compileSdk 36

    defaultConfig {
        applicationId "com.dele.spanishlearning"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
